alias .='ls'
alias ..='cd ..'
alias vimrc='~/.vimrc'

alias tartarus='ssh vyscond@localhost -p 2200'

export ANDROID_HOME=/Users/vyscond/Library/Android/sdk
export PATH=/Users/vyscond/Library/Android/sdk/tools:$PATH
export PATH=/Users/vyscond/Library/Android/sdk/platform-tools:$PATH
export PATH=/Users/vyscond/Applications/Genymotion.app/Contents/MacOS/player.app/Contents/MacOS:$PATH
export PATH=/Users/vyscond/Applications/Genymotion\ Shell.app/Contents/MacOS:$PATH
export POSTGRES=/Applications/Postgres.app/Contents/Versions/9.5/bin
export PATH=$POSTGRES:$PATH

###-tns-completion-start-###
if [ -f /Users/vyscond/.tnsrc ]; then 
    source /Users/vyscond/.tnsrc 
fi
###-tns-completion-end-###
PS1='\u@\h \w
\$ '


# The next line updates PATH for the Google Cloud SDK.
source '/Users/vyscond/google-cloud-sdk/path.bash.inc'

# The next line enables shell command completion for gcloud.
source '/Users/vyscond/google-cloud-sdk/completion.bash.inc'
