pull:
	rm inputrc
	rm bashrc
	rm bash_profile
	-cp ~/.inputrc inputrc
	-cp ~/.bashrc bashrc
	-cp ~/.bash_profile bash_profile

install:
	cp -rf bash_profile ~/.bash_profile
	cp -rf inputrc ~/.inputrc
